version: '3.7'

services:
    api:
        build:
            context: ../packages/api
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT}:9000'
        volumes:
            - .:/app
            - /app/node_modules
