name: Build Checks for CLI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          repository: BRAVO68WEB/b68
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
      - name: Setup Environment
        uses: ./.github/actions/setup
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install -g yarn
      - run: cd packages/cli/ && yarn && yarn build && yarn g:install
      - run: b68 help
      - run: du -sh